//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.08.18 at 04:30:47 PM GMT-03:00 
//


package hPE.location;

import javax.xml.bind.annotation.XmlRegistry;

import hPE.location.ObjectFactory;
import hPE.location.Packages;
import hPE.location.Packages.Package;
import hPE.location.Packages.Package.Components;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the location package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: location
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackagesPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createPackagesPackageComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link Packages }
     * 
     */
    public Packages createPackages() {
        return new Packages();
    }

}
