/* Generated By:JavaCC: Do not edit this line. HCLParserConstants.java */
package hPE.frontend.HCL.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HCLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXTENDS = 1;
  /** RegularExpression Id. */
  int IMPLEMENTS = 2;
  /** RegularExpression Id. */
  int SET = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int DOT = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int OCURV = 7;
  /** RegularExpression Id. */
  int CCURV = 8;
  /** RegularExpression Id. */
  int OSQUARE = 9;
  /** RegularExpression Id. */
  int CSQUARE = 10;
  /** RegularExpression Id. */
  int SLICE = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int UNIT = 13;
  /** RegularExpression Id. */
  int IMPORT = 14;
  /** RegularExpression Id. */
  int COMPUTATION = 15;
  /** RegularExpression Id. */
  int DATA = 16;
  /** RegularExpression Id. */
  int ARCHITECTURE = 17;
  /** RegularExpression Id. */
  int ENVIRONMENT = 18;
  /** RegularExpression Id. */
  int QUALIFIER = 19;
  /** RegularExpression Id. */
  int SYNCHRONIZER = 20;
  /** RegularExpression Id. */
  int APPLICATION = 21;
  /** RegularExpression Id. */
  int ENUMERATOR = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int NEWLINE = 24;
  /** RegularExpression Id. */
  int TABULATION = 25;
  /** RegularExpression Id. */
  int SPACE = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSIDE_COMMENT_2 = 1;
  /** Lexical state. */
  int INSIDE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"extends\"",
    "\"implements\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"slice\"",
    "\"from\"",
    "\"unit\"",
    "\"import\"",
    "\"computation\"",
    "\"data\"",
    "\"architecture\"",
    "\"environment\"",
    "\"qualifier\"",
    "\"synchronizer\"",
    "\"application\"",
    "\"enumerator\"",
    "<ID>",
    "<NEWLINE>",
    "\"\\t\"",
    "\" \"",
    "\"/*\"",
    "\"//\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 31>",
    "<token of kind 32>",
  };

}
