// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BackendServices {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using br.ufc.mdcc.hpcshelf.core;

    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BackendServicesSoap", Namespace="http://tempuri.org/")]
    public partial class BackendServices :  System.Web.Services.Protocols.SoapHttpClientProtocol, IBackendServices {
        
        private System.Threading.SendOrPostCallback howManyRunningPlatformsOperationCompleted;
        
        private System.Threading.SendOrPostCallback killPlatformOperationCompleted;
        
        private System.Threading.SendOrPostCallback deployOperationCompleted;
        
        /// CodeRemarks
        public BackendServices() {
            this.Url = "http://127.0.0.1:8081/BackendServices.asmx";
        }
        
        public BackendServices(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event howManyRunningPlatformsCompletedEventHandler howManyRunningPlatformsCompleted;
        
        /// CodeRemarks
        public event killPlatformCompletedEventHandler killPlatformCompleted;
        
        /// CodeRemarks
        public event deployCompletedEventHandler deployCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/howManyRunningPlatforms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int howManyRunningPlatforms() {
            object[] results = this.Invoke("howManyRunningPlatforms", new object[0]);
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        public void howManyRunningPlatformsAsync() {
            this.howManyRunningPlatformsAsync(null);
        }
        
        /// CodeRemarks
        public void howManyRunningPlatformsAsync(object userState) {
            if ((this.howManyRunningPlatformsOperationCompleted == null)) {
                this.howManyRunningPlatformsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhowManyRunningPlatformsOperationCompleted);
            }
            this.InvokeAsync("howManyRunningPlatforms", new object[0], this.howManyRunningPlatformsOperationCompleted, userState);
        }
        
        private void OnhowManyRunningPlatformsOperationCompleted(object arg) {
            if ((this.howManyRunningPlatformsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.howManyRunningPlatformsCompleted(this, new howManyRunningPlatformsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/killPlatform", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int killPlatform(int killed) {
            object[] results = this.Invoke("killPlatform", new object[] {
                        killed});
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        public void killPlatformAsync(int killed) {
            this.killPlatformAsync(killed, null);
        }
        
        /// CodeRemarks
        public void killPlatformAsync(int killed, object userState) {
            if ((this.killPlatformOperationCompleted == null)) {
                this.killPlatformOperationCompleted = new System.Threading.SendOrPostCallback(this.OnkillPlatformOperationCompleted);
            }
            this.InvokeAsync("killPlatform", new object[] {
                        killed}, this.killPlatformOperationCompleted, userState);
        }
        
        private void OnkillPlatformOperationCompleted(object arg) {
            if ((this.killPlatformCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.killPlatformCompleted(this, new killPlatformCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deploy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string deploy(string str_nodes) {
            object[] results = this.Invoke("deploy", new object[] {
                        str_nodes});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void deployAsync(string str_nodes) {
            this.deployAsync(str_nodes, null);
        }
        
        /// CodeRemarks
        public void deployAsync(string str_nodes, object userState) {
            if ((this.deployOperationCompleted == null)) {
                this.deployOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeployOperationCompleted);
            }
            this.InvokeAsync("deploy", new object[] {
                        str_nodes}, this.deployOperationCompleted, userState);
        }
        
        private void OndeployOperationCompleted(object arg) {
            if ((this.deployCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deployCompleted(this, new deployCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void howManyRunningPlatformsCompletedEventHandler(object sender, howManyRunningPlatformsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class howManyRunningPlatformsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal howManyRunningPlatformsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void killPlatformCompletedEventHandler(object sender, killPlatformCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class killPlatformCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal killPlatformCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void deployCompletedEventHandler(object sender, deployCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deployCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deployCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
