//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.29 at 08:17:30 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/packages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hPE.location.xml;
