// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/Instantiator")]
    [System.Xml.Serialization.XmlRootAttribute("application", Namespace="http://www.example.org/Instantiator")]
    public partial class ComponentFunctorApplicationType {
        
        private string library_pathField;
        
        private ContextParameterType[] context_parameterField;
        
        private int[] nodeField;
        
        private UnitMappingType[] unit_mappingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string library_path {
            get {
                return this.library_pathField;
            }
            set {
                this.library_pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("context_parameter")]
        public ContextParameterType[] context_parameter {
            get {
                return this.context_parameterField;
            }
            set {
                this.context_parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public int[] node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit_mapping")]
        public UnitMappingType[] unit_mapping {
            get {
                return this.unit_mappingField;
            }
            set {
                this.unit_mappingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/Instantiator")]
    public partial class ContextParameterType {
        
        private string formal_parameter_idField;
        
        private ComponentFunctorApplicationType actual_parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formal_parameter_id {
            get {
                return this.formal_parameter_idField;
            }
            set {
                this.formal_parameter_idField = value;
            }
        }
        
        /// <remarks/>
        public ComponentFunctorApplicationType actual_parameter {
            get {
                return this.actual_parameterField;
            }
            set {
                this.actual_parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/Instantiator")]
    public partial class UnitMappingType {
        
        private string unit_idField;
        
        private int unit_indexField;
        
        private int[] nodeField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                this.unit_idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int unit_index {
            get {
                return this.unit_indexField;
            }
            set {
                this.unit_indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public int[] node {
            get {
                return this.nodeField1;
            }
            set {
                this.nodeField1 = value;
            }
        }
    }
}
