// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Instantiator {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    [System.Xml.Serialization.XmlRootAttribute("application", Namespace="http://www.example.org/instantiator", IsNullable=false)]
    public partial class InstanceType {
        
        private string instance_refField;
        
        private ComponentFunctorApplicationType contextual_typeField;
        
        private UnitMappingType[] unit_mappingField;
        
        private FacetAddressType[] facet_addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string instance_ref {
            get {
                return this.instance_refField;
            }
            set {
                this.instance_refField = value;
            }
        }
        
        /// <remarks/>
        public ComponentFunctorApplicationType contextual_type {
            get {
                return this.contextual_typeField;
            }
            set {
                this.contextual_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit_mapping")]
        public UnitMappingType[] unit_mapping {
            get {
                return this.unit_mappingField;
            }
            set {
                this.unit_mappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facet_address")]
        public FacetAddressType[] facet_address {
            get {
                return this.facet_addressField;
            }
            set {
                this.facet_addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ComponentFunctorApplicationType {
        
        private string component_refField;
        
        private ContextArgumentType[] argumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string component_ref {
            get {
                return this.component_refField;
            }
            set {
                this.component_refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("argument")]
        public ContextArgumentType[] argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ContextArgumentType {
        
        private string parameter_idField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string parameter_id {
            get {
                return this.parameter_idField;
            }
            set {
                this.parameter_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(ComponentFunctorApplicationType))]
        [System.Xml.Serialization.XmlElementAttribute("variable", Type=typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class UnitMappingType {
        
        private string unit_idField;
        
        private int unit_indexField;
        
        private int[] nodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                this.unit_idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int unit_index {
            get {
                return this.unit_indexField;
            }
            set {
                this.unit_indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public int[] node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class FacetAddressType {
        
        private string addressField;
        
        private int portField;
        
        private bool portSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool portSpecified {
            get {
                return this.portSpecifiedField;
            }
            set {
                this.portSpecifiedField = value;
            }
        }
    }
}
