// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SAFeSWL {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlRootAttribute("architecture", Namespace="http://www.example.org/SAFe_architecture_V3", IsNullable=false)]
    public partial class Architecture {
        
        private EnvPort[] applicationField;
        
        private EnvPort[] workflowField;
        
        private Component[] bodyField;
        
        private env_bindingType[] env_bindingField;
        
        private task_bindingType[] task_bindingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="envPort", IsNullable=false)]
        public EnvPort[] application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="envPort", IsNullable=false)]
        public EnvPort[] workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="computation", Type=typeof(Computation), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="connector", Type=typeof(Connector), IsNullable=false)]
        public Component[] body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("env_binding")]
        public env_bindingType[] env_binding {
            get {
                return this.env_bindingField;
            }
            set {
                this.env_bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task_binding")]
        public task_bindingType[] task_binding {
            get {
                return this.task_bindingField;
            }
            set {
                this.task_bindingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsesPort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvidesPort))]
    public partial class EnvPort : Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnvPort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsesPort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvidesPort))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskPort))]
    public partial class Port {
        
        private PortType typeField;
        
        private bool typeSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public PortType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool typeSpecified {
            get {
                return this.typeSpecifiedField;
            }
            set {
                this.typeSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public enum PortType {
        
        /// <remarks/>
        environment,
        
        /// <remarks/>
        task,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class UsesPort : EnvPort {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class ProvidesPort : EnvPort {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class TaskPort : Port {
        
        private Action[] actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action")]
        public Action[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class Action {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class Computation : Worker {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computation))]
    public partial class Worker : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlRootAttribute("ArrayOfEnvPort", Namespace="http://www.example.org/SAFe_architecture_V3")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Worker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Application))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Workflow))]
    public partial class Component {
        
        private EnvPort[] envPortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("envPort")]
        public EnvPort[] envPort {
            get {
                return this.envPortField;
            }
            set {
                this.envPortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class Connector : Worker {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class Application : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class Workflow : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class env_bindingType {
        
        private UsesPort usesField;
        
        private ProvidesPort providesField;
        
        /// <remarks/>
        public UsesPort uses {
            get {
                return this.usesField;
            }
            set {
                this.usesField = value;
            }
        }
        
        /// <remarks/>
        public ProvidesPort provides {
            get {
                return this.providesField;
            }
            set {
                this.providesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V3")]
    public partial class task_bindingType {
        
        private TaskPort task_AField;
        
        private TaskPort task_BField;
        
        /// <remarks/>
        public TaskPort task_A {
            get {
                return this.task_AField;
            }
            set {
                this.task_AField = value;
            }
        }
        
        /// <remarks/>
        public TaskPort task_B {
            get {
                return this.task_BField;
            }
            set {
                this.task_BField = value;
            }
        }
    }
}
