// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SAFeSWL {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    [System.Xml.Serialization.XmlRootAttribute("architecture", Namespace="http://www.example.org/SAFe_architecture_V2", IsNullable=false)]
    public partial class Architecture {
        
        private string application_nameField;
        
        private Application applicationField;
        
        private Workflow workflowField;
        
        private Component[] bodyField;
        
        private ArchitectureEnv_binding[] env_bindingField;
        
        private ArchitectureTask_binding[] task_bindingField;
        
        /// <remarks>
///It is the qualified name of the application, given by the application provider.
///</remarks>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string application_name {
            get {
                return this.application_nameField;
            }
            set {
                this.application_nameField = value;
            }
        }
        
        /// <remarks/>
        public Application application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public Workflow workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="computation", Type=typeof(Computation), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="repository", Type=typeof(Repository), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="qualifier", Type=typeof(Qualifier), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="platform", Type=typeof(Platform), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="connector", Type=typeof(Connector), IsNullable=false)]
        public Component[] body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("env_binding")]
        public ArchitectureEnv_binding[] env_binding {
            get {
                return this.env_bindingField;
            }
            set {
                this.env_bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task_binding")]
        public ArchitectureTask_binding[] task_binding {
            get {
                return this.task_bindingField;
            }
            set {
                this.task_bindingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Application : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Platform))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Qualifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Repository))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Application))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Workflow))]
    public partial class Component {
        
        private string nameField;
        
        private int idField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private Port[][] itemsField;
        
        private ComponentContract contractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("env_ports")]
        [System.Xml.Serialization.XmlElementAttribute("task_ports")]
        [System.Xml.Serialization.XmlChoiceIdentifier("ItemsElementName")]
        public Port[][] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ComponentContract contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        env_ports,
        
        /// <remarks/>
        task_ports,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class PortUses : Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortProvides))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortUses))]
    public partial class Port {
        
        private string nameField1;
        
        private int idField1;
        
        private PortAction[] actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField1;
            }
            set {
                this.idField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action")]
        public PortAction[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class PortAction {
        
        private string nameField2;
        
        private int idField2;
        
        private bool idSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField2;
            }
            set {
                this.nameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField2;
            }
            set {
                this.idField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField;
            }
            set {
                this.idSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class PortProvides : Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class ComponentContract {
        
        private int idField3;
        
        private bool idSpecifiedField1;
        
        private string nameField3;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField3;
            }
            set {
                this.idField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField1;
            }
            set {
                this.idSpecifiedField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField3;
            }
            set {
                this.nameField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Connector : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Platform : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Qualifier : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Repository : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Computation : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class Workflow : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class ArchitectureEnv_binding : BindingType {
        
        private PortUses usesField;
        
        private PortProvides providesField;
        
        /// <remarks/>
        public PortUses uses {
            get {
                return this.usesField;
            }
            set {
                this.usesField = value;
            }
        }
        
        /// <remarks/>
        public PortProvides provides {
            get {
                return this.providesField;
            }
            set {
                this.providesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchitectureEnv_binding))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchitectureTask_binding))]
    public partial class BindingType {
        
        private int idField4;
        
        private bool idSpecifiedField2;
        
        private string nameField4;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField4;
            }
            set {
                this.idField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField2;
            }
            set {
                this.idSpecifiedField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField4;
            }
            set {
                this.nameField4 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V2")]
    public partial class ArchitectureTask_binding : BindingType {
        
        private Port task_AField;
        
        private Port task_BField;
        
        /// <remarks/>
        public Port task_A {
            get {
                return this.task_AField;
            }
            set {
                this.task_AField = value;
            }
        }
        
        /// <remarks/>
        public Port task_B {
            get {
                return this.task_BField;
            }
            set {
                this.task_BField = value;
            }
        }
    }
}
