// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SAFeSWL {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    [System.Xml.Serialization.XmlRootAttribute("architecture", Namespace="http://www.example.org/SAFe_architecture_V4", IsNullable=false)]
    public partial class Architecture {
        
        private string application_nameField;
        
        private Component applicationField;
        
        private Component workflowField;
        
        private Component[] bodyField;
        
        private BindingEnvironment[] env_bindingField;
        
        private BindingTask[] task_bindingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string application_name {
            get {
                return this.application_nameField;
            }
            set {
                this.application_nameField = value;
            }
        }
        
        /// <remarks/>
        public Component application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public Component workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="computation", Type=typeof(Computation), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="repository", Type=typeof(Repository), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="connector", Type=typeof(Connector), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="platform", Type=typeof(Platform), IsNullable=false)]
        public Component[] body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("env_binding")]
        public BindingEnvironment[] env_binding {
            get {
                return this.env_bindingField;
            }
            set {
                this.env_bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task_binding")]
        public BindingTask[] task_binding {
            get {
                return this.task_bindingField;
            }
            set {
                this.task_bindingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Platform))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Worker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Repository))]
    public partial class Component {
        
        private string nameField;
        
        private int idField;
        
        private bool idSpecifiedField;
        
        private PortEnvironmentUses[] uses_portField;
        
        private PortEnvironmentProvides[] provides_portField;
        
        private Contract contractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField;
            }
            set {
                this.idSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uses_port")]
        public PortEnvironmentUses[] uses_port {
            get {
                return this.uses_portField;
            }
            set {
                this.uses_portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provides_port")]
        public PortEnvironmentProvides[] provides_port {
            get {
                return this.provides_portField;
            }
            set {
                this.provides_portField = value;
            }
        }
        
        /// <remarks/>
        public Contract contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class PortEnvironmentUses : PortEnvironment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortEnvironmentUses))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortEnvironmentProvides))]
    public partial class PortEnvironment : Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortEnvironment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortEnvironmentUses))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortEnvironmentProvides))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PortTask))]
    public partial class Port {
        
        private int idField1;
        
        private bool idSpecifiedField1;
        
        private int id_componentField;
        
        private bool id_componentSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField1;
            }
            set {
                this.idField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField1;
            }
            set {
                this.idSpecifiedField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id_component {
            get {
                return this.id_componentField;
            }
            set {
                this.id_componentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool id_componentSpecified {
            get {
                return this.id_componentSpecifiedField;
            }
            set {
                this.id_componentSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class PortEnvironmentProvides : PortEnvironment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class PortTask : Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class Contract {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uri", Type=typeof(string), DataType="anyURI")]
        [System.Xml.Serialization.XmlElementAttribute("instantiation_type", Type=typeof(InstanceType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
    public partial class InstanceType {
        
        private string instance_refField;
        
        private ComponentFunctorApplicationType contextual_typeField;
        
        private UnitMappingType[] unit_mappingField;
        
        private FacetAddressType[] facet_addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string instance_ref {
            get {
                return this.instance_refField;
            }
            set {
                this.instance_refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComponentFunctorApplicationType contextual_type {
            get {
                return this.contextual_typeField;
            }
            set {
                this.contextual_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit_mapping", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitMappingType[] unit_mapping {
            get {
                return this.unit_mappingField;
            }
            set {
                this.unit_mappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facet_address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacetAddressType[] facet_address {
            get {
                return this.facet_addressField;
            }
            set {
                this.facet_addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ComponentFunctorApplicationType {
        
        private string component_refField;
        
        private ContextArgumentType[] argumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string component_ref {
            get {
                return this.component_refField;
            }
            set {
                this.component_refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("argument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContextArgumentType[] argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ContextArgumentType {
        
        private string parameter_idField;
        
        private object itemField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string parameter_id {
            get {
                return this.parameter_idField;
            }
            set {
                this.parameter_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", Type=typeof(ComponentFunctorApplicationType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("variable", Type=typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item {
            get {
                return this.itemField1;
            }
            set {
                this.itemField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class UnitMappingType {
        
        private string unit_idField;
        
        private int unit_indexField;
        
        private int[] nodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                this.unit_idField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int unit_index {
            get {
                return this.unit_indexField;
            }
            set {
                this.unit_indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class FacetAddressType {
        
        private string addressField;
        
        private int portField;
        
        private bool portSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool portSpecified {
            get {
                return this.portSpecifiedField;
            }
            set {
                this.portSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class Platform : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computation))]
    public partial class Worker : Component {
        
        private PortTask[] task_portField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task_port")]
        public PortTask[] task_port {
            get {
                return this.task_portField;
            }
            set {
                this.task_portField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class Connector : Worker {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class Computation : Worker {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class Repository : Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class BindingEnvironment {
        
        private int idField2;
        
        private bool idSpecifiedField2;
        
        private PortEnvironmentUses uses_portField1;
        
        private PortEnvironmentProvides provides_portField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField2;
            }
            set {
                this.idField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField2;
            }
            set {
                this.idSpecifiedField2 = value;
            }
        }
        
        /// <remarks/>
        public PortEnvironmentUses uses_port {
            get {
                return this.uses_portField1;
            }
            set {
                this.uses_portField1 = value;
            }
        }
        
        /// <remarks/>
        public PortEnvironmentProvides provides_port {
            get {
                return this.provides_portField1;
            }
            set {
                this.provides_portField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V4")]
    public partial class BindingTask {
        
        private int idField3;
        
        private bool idSpecifiedField3;
        
        private PortTask left_peerField;
        
        private PortTask right_peerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int id {
            get {
                return this.idField3;
            }
            set {
                this.idField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool idSpecified {
            get {
                return this.idSpecifiedField3;
            }
            set {
                this.idSpecifiedField3 = value;
            }
        }
        
        /// <remarks/>
        public PortTask left_peer {
            get {
                return this.left_peerField;
            }
            set {
                this.left_peerField = value;
            }
        }
        
        /// <remarks/>
        public PortTask right_peer {
            get {
                return this.right_peerField;
            }
            set {
                this.right_peerField = value;
            }
        }
    }
}
