// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace br.ufc.mdcc.hpe.CoreService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PlatformSoap", Namespace="http://tempuri.org/")]
    public partial class PlatformAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
		public PlatformAccess() {
            this.Url = "http://localhost:8080/Platform.asmx";
        }
        
		public PlatformAccess(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deploy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string deploy(string component_info) {
            object[] results = this.Invoke("deploy", new object[] {
                        component_info});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begindeploy(string component_info, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deploy", new object[] {
                        component_info}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Enddeploy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/instantiate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string instantiate(string instance_info) {
            object[] results = this.Invoke("instantiate", new object[] {
                        instance_info});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begininstantiate(string instance_info, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("instantiate", new object[] {
                        instance_info}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Endinstantiate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
