/**
 *
 * $Id$
 */
package hPE.xml.component.validation;

import hPE.xml.component.InnerComponentType;
import hPE.xml.component.ParameterRenaming;
import hPE.xml.component.UnitBoundsType;
import hPE.xml.component.VisualElementAttributes;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hPE.xml.component.ComponentInUseType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentInUseTypeValidator {
	boolean validate();

	boolean validateVisualDescription(VisualElementAttributes value);
	boolean validateParameter(EList<ParameterRenaming> value);
	boolean validatePort(EList<InnerComponentType> value);
	boolean validateUnitBounds(EList<UnitBoundsType> value);
	boolean validateHashComponentUID(String value);
	boolean validateLocalRef(String value);
	boolean validateLocation(String value);
	boolean validateMultiple(boolean value);
	boolean validateName(String value);
	boolean validatePackage(String value);
	boolean validateParameterId(String value);
	boolean validateVersion(String value);
}
