/**
 *
 * $Id$
 */
package hPE.xml.component.validation;


/**
 * A sample validator interface for {@link hPE.xml.component.EnumerableUnitSliceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumerableUnitSliceTypeValidator {
	boolean validate();

	boolean validateCRef(String value);
	boolean validateSplitReplica(int value);
	boolean validateSRef(String value);
	boolean validateURef(String value);
}
