/**
 *
 * $Id$
 */
package hPE.xml.component.validation;

import hPE.xml.component.EnumerableType;
import hPE.xml.component.EnumeratorFromRecursionType;
import hPE.xml.component.VisualElementAttributes;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hPE.xml.component.EnumeratorType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumeratorTypeValidator {
	boolean validate();

	boolean validateOriginRef(EList<String> value);
	boolean validateLinks(EList<EnumerableType> value);
	boolean validateVisualDescription(VisualElementAttributes value);
	boolean validateFromRecursion(EnumeratorFromRecursionType value);
	boolean validateCardinality(int value);
	boolean validateFromSplit(boolean value);
	boolean validateRef(String value);
	boolean validateVarId(String value);
}
