/**
 *
 * $Id$
 */
package hPE.xml.component.validation;

import hPE.xml.component.ConditionType;
import hPE.xml.component.GuardType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link hPE.xml.component.GuardType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GuardTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateCondition(EList<ConditionType> value);
	boolean validateAnd(EList<GuardType> value);
	boolean validateOr(EList<GuardType> value);
	boolean validateNot(boolean value);
}
