/**
 *
 * $Id$
 */
package hPE.xml.component.validation;


/**
 * A sample validator interface for {@link hPE.xml.component.InnerRenamingType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InnerRenamingTypeValidator {
	boolean validate();

	boolean validateCNewName(String value);
	boolean validateCOldName(String value);
	boolean validateCRef(String value);

	boolean validateIndexReplica(int value);
}
