/**
 *
 * $Id$
 */
package hPE.xml.component.validation;

import hPE.xml.component.SourceFileType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hPE.xml.component.SourceType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceTypeValidator {
	boolean validate();

	boolean validateFile(EList<SourceFileType> value);
	boolean validateSourceType(String value);
	boolean validateVersionId(String value);
}
