/**
 *
 * $Id$
 */
package hPE.xml.component.validation;

import hPE.xml.component.UnitRefType;
import hPE.xml.component.UnitSliceType;
import hPE.xml.component.VisualElementAttributes;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hPE.xml.component.UnitType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitTypeValidator {
	boolean validate();

	boolean validateSuper(UnitRefType value);
	boolean validateSlices(EList<UnitSliceType> value);
	boolean validateVisualDescription(VisualElementAttributes value);
	boolean validateFacet(int value);

	boolean validateIRef(String value);
	boolean validateMultiple(boolean value);
	boolean validatePrivate(boolean value);
	boolean validateReplica(int value);
	boolean validateURef(String value);
	boolean validateVisibleInterface(boolean value);
}
