// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TestService.CoreService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreSoap", Namespace="http://ComponentRepository.hpe.mdcc.ufc.br/")]
    public partial class Core : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public Core() {
            this.Url = "http://127.0.0.1:8080/Core.asmx";
        }

        
        public Core(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/resolve", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] resolve(string contract) {
            object[] results = this.Invoke("resolve", new object[] {
                        contract});
            return ((string[])(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Beginresolve(string contract, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("resolve", new object[] {
                        contract}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string[] Endresolve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/deploy", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string deploy(string arch_desc_xml, string arch_ref, string[] c_ids, string[] c_contracts, string[] c_choices, string[] c_unitmapping, string platform_address_SAFe) {
            object[] results = this.Invoke("deploy", new object[] {
                        arch_desc_xml,
                        arch_ref,
                        c_ids,
                        c_contracts,
                        c_choices,
					    c_unitmapping,
                        platform_address_SAFe});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begindeploy(string arch_desc_xml, string arch_ref, string[] c_ids, string[] c_contracts, string[] c_choices, string platform_address_SAFe, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deploy", new object[] {
                        arch_desc_xml,
                        arch_ref,
                        c_ids,
                        c_contracts,
                        c_choices,
                        platform_address_SAFe}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Enddeploy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/instantiate", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string instantiate(string arch_desc_xml, string arch_ref, string platform_address_SAFe) {
            object[] results = this.Invoke("instantiate", new object[] {
                        arch_desc_xml,
                        arch_ref,
                        platform_address_SAFe});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begininstantiate(string arch_desc_xml, string arch_ref, string platform_address_SAFe, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("instantiate", new object[] {
                        arch_desc_xml,
                        arch_ref,
                        platform_address_SAFe}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Endinstantiate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
