// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TestService.CoreService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CoreSoap", Namespace="http://ComponentRepository.hpe.mdcc.ufc.br/")]
    public partial class Core : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public Core() {
            this.Url = "http://127.0.0.1:8080/Core.asmx";
        }
        
        public Core(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/resolve", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void resolve(int workflow_handle, string c_ref) {
            this.Invoke("resolve", new object[] {
                        workflow_handle,
                        c_ref});
        }
        
        /// CodeRemarks
        public System.IAsyncResult Beginresolve(int workflow_handle, string c_ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("resolve", new object[] {
                        workflow_handle,
                        c_ref}, callback, asyncState);
        }
        
        /// CodeRemarks
        public void Endresolve(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/openWorkflowSession", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int openWorkflowSession(string arch_desc_xml, string SAFe_address) {
            object[] results = this.Invoke("openWorkflowSession", new object[] {
                        arch_desc_xml,
                        SAFe_address});
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginopenWorkflowSession(string arch_desc_xml, string SAFe_address, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("openWorkflowSession", new object[] {
                        arch_desc_xml,
                        SAFe_address}, callback, asyncState);
        }
        
        /// CodeRemarks
        public int EndopenWorkflowSession(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/registerContract", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registerContract(int workflow_handle, string c_ref, string contract, string unit_mapping) {
            this.Invoke("registerContract", new object[] {
                        workflow_handle,
                        c_ref,
                        contract,
                        unit_mapping});
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginregisterContract(int workflow_handle, string c_ref, string contract, string unit_mapping, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("registerContract", new object[] {
                        workflow_handle,
                        c_ref,
                        contract,
                        unit_mapping}, callback, asyncState);
        }
        
        /// CodeRemarks
        public void EndregisterContract(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/closeWorkflowSession", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void closeWorkflowSession(int workflow_handle) {
            this.Invoke("closeWorkflowSession", new object[] {
                        workflow_handle});
        }
        
        /// CodeRemarks
        public System.IAsyncResult BegincloseWorkflowSession(int workflow_handle, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("closeWorkflowSession", new object[] {
                        workflow_handle}, callback, asyncState);
        }
        
        /// CodeRemarks
        public void EndcloseWorkflowSession(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/deploy", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string deploy(int workflow_handle, string arch_ref) {
            object[] results = this.Invoke("deploy", new object[] {
                        workflow_handle,
                        arch_ref});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begindeploy(int workflow_handle, string arch_ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deploy", new object[] {
                        workflow_handle,
                        arch_ref}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Enddeploy(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/run", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void run(int workflow_handle) {
            this.Invoke("run", new object[] {
                        workflow_handle});
        }
        
        /// CodeRemarks
        public System.IAsyncResult Beginrun(int workflow_handle, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("run", new object[] {
                        workflow_handle}, callback, asyncState);
        }
        
        /// CodeRemarks
        public void Endrun(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ComponentRepository.hpe.mdcc.ufc.br/instantiate", RequestNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", ResponseNamespace="http://ComponentRepository.hpe.mdcc.ufc.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string instantiate(int workflow_handle, string arch_ref) {
            object[] results = this.Invoke("instantiate", new object[] {
                        workflow_handle,
                        arch_ref});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult Begininstantiate(int workflow_handle, string arch_ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("instantiate", new object[] {
                        workflow_handle,
                        arch_ref}, callback, asyncState);
        }
        
        /// CodeRemarks
        public string Endinstantiate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
