// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
//namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlRootAttribute("component", Namespace="http://www.example.org/HashComponent", IsNullable=false)]
    public partial class ComponentType {
        
        private ComponentHeaderType headerField;
        
        private object[] componentInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComponentHeaderType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="innerComponent", Type=typeof(InnerComponentType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="parameter", Type=typeof(ParameterType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="supplyParameter", Type=typeof(ParameterSupplyType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="innerRenaming", Type=typeof(InnerRenamingType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="fusion", Type=typeof(FusionType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="split", Type=typeof(SplitType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="recursiveEntry", Type=typeof(RecursiveEntryType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="interface", Type=typeof(InterfaceType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="unit", Type=typeof(UnitType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="enumerator", Type=typeof(EnumeratorType), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="fusionsOfReplicators", Type=typeof(FusionOfReplicatorsType[]), IsNullable=false, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] componentInfo {
            get {
                return this.componentInfoField;
            }
            set {
                this.componentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ComponentHeaderType {
        
        private SupportedKinds kindField;
        
        private bool kindSpecifiedField;
        
        private string nameField;
        
        private string packagePathField;
        
        private string hash_component_UIDField;
        
        private bool isAbstractField;
        
        private bool isAbstractSpecifiedField;
        
        private string locationURIField;
        
        private BaseTypeType baseTypeField;
        
        private VersionType[] versionsField;
        
        private VisualElementAttributes visualAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public SupportedKinds kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool kindSpecified {
            get {
                return this.kindSpecifiedField;
            }
            set {
                this.kindSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="", DataType="anyURI")]
        public string packagePath {
            get {
                return this.packagePathField;
            }
            set {
                this.packagePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string hash_component_UID {
            get {
                return this.hash_component_UIDField;
            }
            set {
                this.hash_component_UIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool isAbstract {
            get {
                return this.isAbstractField;
            }
            set {
                this.isAbstractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool isAbstractSpecified {
            get {
                return this.isAbstractSpecifiedField;
            }
            set {
                this.isAbstractSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="", DataType="anyURI")]
        public string locationURI {
            get {
                return this.locationURIField;
            }
            set {
                this.locationURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BaseTypeType baseType {
            get {
                return this.baseTypeField;
            }
            set {
                this.baseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("versions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VersionType[] versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualAttributes {
            get {
                return this.visualAttributesField;
            }
            set {
                this.visualAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public enum SupportedKinds {
        
        /// <remarks/>
        Data,
        
        /// <remarks/>
        Computation,
        
        /// <remarks/>
        Synchronizer,
        
        /// <remarks/>
        Platform,
        
        /// <remarks/>
        Environment,
        
        /// <remarks/>
        Qualifier,
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        Enumerator,
        
        /// <remarks/>
        Facet,
        
        /// <remarks/>
        Binding,
        
        /// <remarks/>
        Topology,
        
        /// <remarks/>
        value,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class BaseTypeType {
        
        private ExtensionTypeType extensionTypeField;
        
        private ComponentInUseType componentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtensionTypeType extensionType {
            get {
                return this.extensionTypeField;
            }
            set {
                this.extensionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ComponentInUseType component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ExtensionTypeType {
        
        private ItemChoiceType1 itemElementNameField;
        
        private bool itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("implements", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("extends", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifier("ItemElementName")]
        public bool Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemChoiceType", Namespace="http://www.example.org/HashComponent", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        implements,
        
        /// <remarks/>
        extends,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InnerComponentType))]
    public partial class ComponentInUseType {
        
        private string nameField1;
        
        private string versionField;
        
        private string locationField;
        
        private string localRefField;
        
        private string hash_component_UIDField1;
        
        private string parameter_idField;
        
        private string packageField;
        
        private bool multipleField;
        
        private bool multipleSpecifiedField;
        
        private VisualElementAttributes visualDescriptionField;
        
        private ParameterRenaming[] parameterField;
        
        private InnerComponentType[] portField;
        
        private UnitBoundsType[] unitBoundsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="", DataType="ID")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="", DataType="anyURI")]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string localRef {
            get {
                return this.localRefField;
            }
            set {
                this.localRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string hash_component_UID {
            get {
                return this.hash_component_UIDField1;
            }
            set {
                this.hash_component_UIDField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string parameter_id {
            get {
                return this.parameter_idField;
            }
            set {
                this.parameter_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool multiple {
            get {
                return this.multipleField;
            }
            set {
                this.multipleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool multipleSpecified {
            get {
                return this.multipleSpecifiedField;
            }
            set {
                this.multipleSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField;
            }
            set {
                this.visualDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ParameterRenaming[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InnerComponentType[] port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unitBounds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitBoundsType[] unitBounds {
            get {
                return this.unitBoundsField;
            }
            set {
                this.unitBoundsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class VisualElementAttributes {
        
        private uint xField;
        
        private uint yField;
        
        private uint wField;
        
        private uint hField;
        
        private ColorComplexType colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public uint x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public uint y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public uint w {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public uint h {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ColorComplexType color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ColorComplexType {
        
        private byte rField;
        
        private byte gField;
        
        private byte bField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public byte r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public byte g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public byte b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ParameterRenaming {
        
        private string formFieldIdField;
        
        private string varNameField;
        
        private int orderField;
        
        private bool orderSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formFieldId {
            get {
                return this.formFieldIdField;
            }
            set {
                this.formFieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string varName {
            get {
                return this.varNameField;
            }
            set {
                this.varNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool orderSpecified {
            get {
                return this.orderSpecifiedField;
            }
            set {
                this.orderSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InnerComponentType : ComponentInUseType {
        
        private bool exposedField;
        
        private bool exposedSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool exposed {
            get {
                return this.exposedField;
            }
            set {
                this.exposedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool exposedSpecified {
            get {
                return this.exposedSpecifiedField;
            }
            set {
                this.exposedSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class UnitBoundsType {
        
        private string uRefField;
        
        private bool parallelField;
        
        private bool parallelSpecifiedField;
        
        private int slice_replicaField;
        
        private int unit_replicaField;
        
        private uint replicaField;
        
        private VisualElementAttributes visualDescriptionField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField;
            }
            set {
                this.uRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool parallel {
            get {
                return this.parallelField;
            }
            set {
                this.parallelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool parallelSpecified {
            get {
                return this.parallelSpecifiedField;
            }
            set {
                this.parallelSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int slice_replica {
            get {
                return this.slice_replicaField;
            }
            set {
                this.slice_replicaField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int unit_replica {
            get {
                return this.unit_replicaField;
            }
            set {
                this.unit_replicaField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0u)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public uint replica {
            get {
                return this.replicaField;
            }
            set {
                this.replicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField1;
            }
            set {
                this.visualDescriptionField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class VersionType {
        
        private int field1Field;
        
        private bool field1SpecifiedField;
        
        private int field2Field;
        
        private bool field2SpecifiedField;
        
        private int field3Field;
        
        private bool field3SpecifiedField;
        
        private int field4Field;
        
        private bool field4SpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool field1Specified {
            get {
                return this.field1SpecifiedField;
            }
            set {
                this.field1SpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool field2Specified {
            get {
                return this.field2SpecifiedField;
            }
            set {
                this.field2SpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool field3Specified {
            get {
                return this.field3SpecifiedField;
            }
            set {
                this.field3SpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool field4Specified {
            get {
                return this.field4SpecifiedField;
            }
            set {
                this.field4SpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ParameterType {
        
        private string formFieldIdField1;
        
        private string componentRefField;
        
        private string varNameField1;
        
        private int orderField1;
        
        private bool orderSpecifiedField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string formFieldId {
            get {
                return this.formFieldIdField1;
            }
            set {
                this.formFieldIdField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string componentRef {
            get {
                return this.componentRefField;
            }
            set {
                this.componentRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string varName {
            get {
                return this.varNameField1;
            }
            set {
                this.varNameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int order {
            get {
                return this.orderField1;
            }
            set {
                this.orderField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool orderSpecified {
            get {
                return this.orderSpecifiedField1;
            }
            set {
                this.orderSpecifiedField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ParameterSupplyType {
        
        private string varNameField2;
        
        private string cRefField;
        
        private bool directField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string varName {
            get {
                return this.varNameField2;
            }
            set {
                this.varNameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField;
            }
            set {
                this.cRefField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(true)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool direct {
            get {
                return this.directField;
            }
            set {
                this.directField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InnerRenamingType {
        
        private string cRefField1;
        
        private string cOldNameField;
        
        private string cNewNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField1;
            }
            set {
                this.cRefField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cOldName {
            get {
                return this.cOldNameField;
            }
            set {
                this.cOldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cNewName {
            get {
                return this.cNewNameField;
            }
            set {
                this.cNewNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class FusionType {
        
        private string[] cRefsField;
        
        private string pRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cRefs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] cRefs {
            get {
                return this.cRefsField;
            }
            set {
                this.cRefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRef {
            get {
                return this.pRefField;
            }
            set {
                this.pRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class SplitType {
        
        private string eRefField;
        
        private int nField;
        
        private bool nSpecifiedField;
        
        private string cRefPermutationField;
        
        private SplitLinkType[] splitLinkField;
        
        private string[] splitEnumeratorField;
        
        private string[] originRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string eRef {
            get {
                return this.eRefField;
            }
            set {
                this.eRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool nSpecified {
            get {
                return this.nSpecifiedField;
            }
            set {
                this.nSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRefPermutation {
            get {
                return this.cRefPermutationField;
            }
            set {
                this.cRefPermutationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("splitLink", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SplitLinkType[] splitLink {
            get {
                return this.splitLinkField;
            }
            set {
                this.splitLinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("splitEnumerator", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] splitEnumerator {
            get {
                return this.splitEnumeratorField;
            }
            set {
                this.splitEnumeratorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] originRef {
            get {
                return this.originRefField;
            }
            set {
                this.originRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class SplitLinkType {
        
        private string cRefField2;
        
        private string uRefField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField2;
            }
            set {
                this.cRefField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField1;
            }
            set {
                this.uRefField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class RecursiveEntryType {
        
        private string cRefField3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField3;
            }
            set {
                this.cRefField3 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InterfaceType {
        
        private string iRefField;
        
        private int nArgsField;
        
        private bool nArgsSpecifiedField;
        
        private InterfaceSliceType[] sliceField;
        
        private SourceType[] sourcesField;
        
        private VisualElementAttributes visualDescriptionField3;
        
        private InterfacePortType[] portField1;
        
        private string[] externalReferencesField;
        
        private InterfaceParameterType[] parameterField1;
        
        private UnitActionType[] actionField;
        
        private UnitConditionType[] conditionField1;
        
        private ProtocolChoiceType protocolField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string iRef {
            get {
                return this.iRefField;
            }
            set {
                this.iRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int nArgs {
            get {
                return this.nArgsField;
            }
            set {
                this.nArgsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool nArgsSpecified {
            get {
                return this.nArgsSpecifiedField;
            }
            set {
                this.nArgsSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("slice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfaceSliceType[] slice {
            get {
                return this.sliceField;
            }
            set {
                this.sliceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sources", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourceType[] sources {
            get {
                return this.sourcesField;
            }
            set {
                this.sourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField3;
            }
            set {
                this.visualDescriptionField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfacePortType[] port {
            get {
                return this.portField1;
            }
            set {
                this.portField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("externalReferences", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] externalReferences {
            get {
                return this.externalReferencesField;
            }
            set {
                this.externalReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfaceParameterType[] parameter {
            get {
                return this.parameterField1;
            }
            set {
                this.parameterField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitActionType[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitConditionType[] condition {
            get {
                return this.conditionField1;
            }
            set {
                this.conditionField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProtocolChoiceType protocol {
            get {
                return this.protocolField1;
            }
            set {
                this.protocolField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InterfaceSliceType {
        
        private string isRefField;
        
        private InterfaceRefType originRefField1;
        
        private VisualElementAttributes visualDescriptionField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string isRef {
            get {
                return this.isRefField;
            }
            set {
                this.isRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InterfaceRefType originRef {
            get {
                return this.originRefField1;
            }
            set {
                this.originRefField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField2;
            }
            set {
                this.visualDescriptionField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InterfaceRefType {
        
        private string cRefField4;
        
        private string iRefField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField4;
            }
            set {
                this.cRefField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string iRef {
            get {
                return this.iRefField1;
            }
            set {
                this.iRefField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class SourceType {
        
        private string versionIdField;
        
        private string sourceTypeField;
        
        private SourceFileType[] fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="", DataType="ID")]
        public string versionId {
            get {
                return this.versionIdField;
            }
            set {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string sourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourceFileType[] file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class SourceFileType {
        
        private string uriField;
        
        private string srcTypeField;
        
        private string fileTypeField;
        
        private string versionIdField1;
        
        private string nameField2;
        
        private string contentsField;
        
        private string[] dependencyField;
        
        private string[] externalDependencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string srcType {
            get {
                return this.srcTypeField;
            }
            set {
                this.srcTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string fileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string versionId {
            get {
                return this.versionIdField1;
            }
            set {
                this.versionIdField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField2;
            }
            set {
                this.nameField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] dependency {
            get {
                return this.dependencyField;
            }
            set {
                this.dependencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("externalDependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] externalDependency {
            get {
                return this.externalDependencyField;
            }
            set {
                this.externalDependencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InterfacePortType {
        
        private string nameField3;
        
        private VisualElementAttributes visualDescriptionField4;
        
        private PortSliceType[] sliceField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string name {
            get {
                return this.nameField3;
            }
            set {
                this.nameField3 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField4;
            }
            set {
                this.visualDescriptionField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("slice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PortSliceType[] slice {
            get {
                return this.sliceField1;
            }
            set {
                this.sliceField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class PortSliceType {
        
        private string sRefField;
        
        private string pRefField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string sRef {
            get {
                return this.sRefField;
            }
            set {
                this.sRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string pRef {
            get {
                return this.pRefField1;
            }
            set {
                this.pRefField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class InterfaceParameterType {
        
        private string paridField;
        
        private string varidField;
        
        private string inameField;
        
        private string unameField;
        
        private int orderField2;
        
        private bool orderSpecifiedField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string parid {
            get {
                return this.paridField;
            }
            set {
                this.paridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string varid {
            get {
                return this.varidField;
            }
            set {
                this.varidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string iname {
            get {
                return this.inameField;
            }
            set {
                this.inameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uname {
            get {
                return this.unameField;
            }
            set {
                this.unameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int order {
            get {
                return this.orderField2;
            }
            set {
                this.orderField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool orderSpecified {
            get {
                return this.orderSpecifiedField2;
            }
            set {
                this.orderSpecifiedField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class UnitActionType {
        
        private string idField;
        
        private ProtocolChoiceType protocolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProtocolChoiceType protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ProtocolChoiceType {
        
        private ItemChoiceType itemElementNameField1;
        
        private ProtocolType itemField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField1;
            }
            set {
                this.itemElementNameField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("par", Type=typeof(ProtocolCombinatorVisualType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("seq", Type=typeof(ProtocolCombinatorVisualType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("alt", Type=typeof(ProtocolCombinatorVisualType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("perform", Type=typeof(ProtocolPerformVisualType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifier("ItemElementName")]
        public ProtocolType Item {
            get {
                return this.itemField1;
            }
            set {
                this.itemField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        par,
        
        /// <remarks/>
        seq,
        
        /// <remarks/>
        alt,
        
        /// <remarks/>
        perform,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ProtocolCombinatorVisualType : ProtocolCombinatorType {
        
        private VisualElementAttributes visualDescriptionField5;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField5;
            }
            set {
                this.visualDescriptionField5 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolCombinatorVisualType))]
    public partial class ProtocolCombinatorType : ProtocolType {
        
        private ProtocolChoiceType[] actionField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProtocolChoiceType[] action {
            get {
                return this.actionField1;
            }
            set {
                this.actionField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolPerformType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolPerformVisualType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolCombinatorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolCombinatorVisualType))]
    public partial class ProtocolType {
        
        private bool repeatField;
        
        private bool repeatSpecifiedField;
        
        private string idField1;
        
        private GuardType guardField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool repeat {
            get {
                return this.repeatField;
            }
            set {
                this.repeatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool repeatSpecified {
            get {
                return this.repeatSpecifiedField;
            }
            set {
                this.repeatSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string id {
            get {
                return this.idField1;
            }
            set {
                this.idField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuardType guard {
            get {
                return this.guardField;
            }
            set {
                this.guardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GuardConditionType))]
    public partial class GuardType {
        
        private bool notField;
        
        private bool notSpecifiedField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool not {
            get {
                return this.notField;
            }
            set {
                this.notField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool notSpecified {
            get {
                return this.notSpecifiedField;
            }
            set {
                this.notSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition", Type=typeof(ConditionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("and", Type=typeof(GuardType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("or", Type=typeof(GuardType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        condition,
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ConditionType {
        
        private string slice_idField;
        
        private string cond_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string slice_id {
            get {
                return this.slice_idField;
            }
            set {
                this.slice_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cond_id {
            get {
                return this.cond_idField;
            }
            set {
                this.cond_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class GuardConditionType : GuardType {
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProtocolPerformVisualType))]
    public partial class ProtocolPerformType : ProtocolType {
        
        private string action_idField;
        
        private string slice_idField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string action_id {
            get {
                return this.action_idField;
            }
            set {
                this.action_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string slice_id {
            get {
                return this.slice_idField1;
            }
            set {
                this.slice_idField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class ProtocolPerformVisualType : ProtocolPerformType {
        
        private VisualElementAttributes visualDescriptionField6;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField6;
            }
            set {
                this.visualDescriptionField6 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class UnitConditionType {
        
        private string idField2;
        
        private GuardType guardField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string id {
            get {
                return this.idField2;
            }
            set {
                this.idField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GuardType guard {
            get {
                return this.guardField1;
            }
            set {
                this.guardField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class UnitType {
        
        private string uRefField2;
        
        private string iRefField2;
        
        private bool privateField;
        
        private bool privateSpecifiedField;
        
        private bool visibleInterfaceField;
        
        private bool multipleField1;
        
        private bool multipleSpecifiedField1;
        
        private int replicaField1;
        
        private bool replicaSpecifiedField;
        
        private int facetField;
        
        private UnitRefType superField;
        
        private UnitSliceType[] slicesField;
        
        private VisualElementAttributes visualDescriptionField8;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField2;
            }
            set {
                this.uRefField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string iRef {
            get {
                return this.iRefField2;
            }
            set {
                this.iRefField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool @private {
            get {
                return this.privateField;
            }
            set {
                this.privateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool privateSpecified {
            get {
                return this.privateSpecifiedField;
            }
            set {
                this.privateSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(true)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool visibleInterface {
            get {
                return this.visibleInterfaceField;
            }
            set {
                this.visibleInterfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool multiple {
            get {
                return this.multipleField1;
            }
            set {
                this.multipleField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool multipleSpecified {
            get {
                return this.multipleSpecifiedField1;
            }
            set {
                this.multipleSpecifiedField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int replica {
            get {
                return this.replicaField1;
            }
            set {
                this.replicaField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool replicaSpecified {
            get {
                return this.replicaSpecifiedField;
            }
            set {
                this.replicaSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitRefType super {
            get {
                return this.superField;
            }
            set {
                this.superField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("slices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UnitSliceType[] slices {
            get {
                return this.slicesField;
            }
            set {
                this.slicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField8;
            }
            set {
                this.visualDescriptionField8 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitSliceType))]
    public partial class UnitRefType {
        
        private string cRefField5;
        
        private string uRefField3;
        
        private int slice_replicaField1;
        
        private int replicaField2;
        
        private bool replicaSpecifiedField1;
        
        private int inner_replicaField;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("this")]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField5;
            }
            set {
                this.cRefField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField3;
            }
            set {
                this.uRefField3 = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int slice_replica {
            get {
                return this.slice_replicaField1;
            }
            set {
                this.slice_replicaField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int replica {
            get {
                return this.replicaField2;
            }
            set {
                this.replicaField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool replicaSpecified {
            get {
                return this.replicaSpecifiedField1;
            }
            set {
                this.replicaSpecifiedField1 = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue(0)]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int inner_replica {
            get {
                return this.inner_replicaField;
            }
            set {
                this.inner_replicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class UnitSliceType : UnitRefType {
        
        private string sliceNameField;
        
        private bool transitiveField;
        
        private bool transitiveSpecifiedField;
        
        private VisualElementAttributes visualDescriptionField7;
        
        private string[] portField2;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string sliceName {
            get {
                return this.sliceNameField;
            }
            set {
                this.sliceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool transitive {
            get {
                return this.transitiveField;
            }
            set {
                this.transitiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool transitiveSpecified {
            get {
                return this.transitiveSpecifiedField;
            }
            set {
                this.transitiveSpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField7;
            }
            set {
                this.visualDescriptionField7 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] port {
            get {
                return this.portField2;
            }
            set {
                this.portField2 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumeratorType {
        
        private string refField;
        
        private string varIdField;
        
        private int cardinalityField;
        
        private bool cardinalitySpecifiedField;
        
        private bool fromSplitField;
        
        private string[] originRefField2;
        
        private EnumerableType[] linksField;
        
        private VisualElementAttributes visualDescriptionField9;
        
        private EnumeratorFromRecursionType fromRecursionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValue("*")]
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string varId {
            get {
                return this.varIdField;
            }
            set {
                this.varIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int cardinality {
            get {
                return this.cardinalityField;
            }
            set {
                this.cardinalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool cardinalitySpecified {
            get {
                return this.cardinalitySpecifiedField;
            }
            set {
                this.cardinalitySpecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public bool fromSplit {
            get {
                return this.fromSplitField;
            }
            set {
                this.fromSplitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] originRef {
            get {
                return this.originRefField2;
            }
            set {
                this.originRefField2 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("links", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnumerableType[] links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VisualElementAttributes visualDescription {
            get {
                return this.visualDescriptionField9;
            }
            set {
                this.visualDescriptionField9 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnumeratorFromRecursionType fromRecursion {
            get {
                return this.fromRecursionField;
            }
            set {
                this.fromRecursionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableUnitType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableComponentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableUnitSliceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableEntryType))]
    public partial class EnumerableType {
        
        private string refField1;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string @ref {
            get {
                return this.refField1;
            }
            set {
                this.refField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumerableUnitType : EnumerableType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumerableComponentType : EnumerableType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumerableUnitSliceType : EnumerableType {
        
        private string uRefField4;
        
        private string cRefField6;
        
        private string sRefField1;
        
        private int splitReplicaField;
        
        private bool splitReplicaSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField4;
            }
            set {
                this.uRefField4 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField6;
            }
            set {
                this.cRefField6 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string sRef {
            get {
                return this.sRefField1;
            }
            set {
                this.sRefField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int splitReplica {
            get {
                return this.splitReplicaField;
            }
            set {
                this.splitReplicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool splitReplicaSpecified {
            get {
                return this.splitReplicaSpecifiedField;
            }
            set {
                this.splitReplicaSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumerableEntryType : EnumerableType {
        
        private string cRefField7;
        
        private string uRefField5;
        
        private int indexField;
        
        private bool indexSpecifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField7;
            }
            set {
                this.cRefField7 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string uRef {
            get {
                return this.uRefField5;
            }
            set {
                this.uRefField5 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public virtual bool indexSpecified {
            get {
                return this.indexSpecifiedField;
            }
            set {
                this.indexSpecifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class EnumeratorFromRecursionType {
        
        private string cRefField8;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
        public string cRef {
            get {
                return this.cRefField8;
            }
            set {
                this.cRefField8 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
    public partial class FusionOfReplicatorsType {
        
        private string eRefField1;
        
        private string[] originRefField3;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eRef {
            get {
                return this.eRefField1;
            }
            set {
                this.eRefField1 = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] originRef {
            get {
                return this.originRefField3;
            }
            set {
                this.originRefField3 = value;
            }
        }
    }
//}
