//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.4927
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
[System.Xml.Serialization.XmlRootAttribute("component", Namespace="http://www.example.org/HashComponent", IsNullable=false)]
public partial class ComponentType {
    
    private ComponentHeaderType headerField;
    
    private object[] componentInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComponentHeaderType header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enumerator", typeof(EnumeratorType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("fusion", typeof(FusionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("fusionsOfReplicators", typeof(FusionsOfReplicatorsType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("innerComponent", typeof(InnerComponentType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("innerRenaming", typeof(InnerRenamingType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("interface", typeof(InterfaceType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("parameter", typeof(ParameterType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("recursiveEntry", typeof(RecursiveEntryType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("split", typeof(SplitType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("supplyParameter", typeof(ParameterSupplyType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("unit", typeof(UnitType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public object[] componentInfo {
        get {
            return this.componentInfoField;
        }
        set {
            this.componentInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ComponentHeaderType {
    
    private BaseTypeType baseTypeField;
    
    private VersionType[] versionsField;
    
    private VisualElementAttributes visualAttributesField;
    
    private SupportedKinds kindField;
    
    private bool kindFieldSpecified;
    
    private string nameField;
    
    private string packagePathField;
    
    private string hash_component_UIDField;
    
    private bool isAbstractField;
    
    private bool isAbstractFieldSpecified;
    
    private string locationURIField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BaseTypeType baseType {
        get {
            return this.baseTypeField;
        }
        set {
            this.baseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("versions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VersionType[] versions {
        get {
            return this.versionsField;
        }
        set {
            this.versionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualAttributes {
        get {
            return this.visualAttributesField;
        }
        set {
            this.visualAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SupportedKinds kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kindSpecified {
        get {
            return this.kindFieldSpecified;
        }
        set {
            this.kindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string packagePath {
        get {
            return this.packagePathField;
        }
        set {
            this.packagePathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hash_component_UID {
        get {
            return this.hash_component_UIDField;
        }
        set {
            this.hash_component_UIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isAbstract {
        get {
            return this.isAbstractField;
        }
        set {
            this.isAbstractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isAbstractSpecified {
        get {
            return this.isAbstractFieldSpecified;
        }
        set {
            this.isAbstractFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string locationURI {
        get {
            return this.locationURIField;
        }
        set {
            this.locationURIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class BaseTypeType {
    
    private ExtensionTypeType extensionTypeField;
    
    private ComponentInUseType componentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExtensionTypeType extensionType {
        get {
            return this.extensionTypeField;
        }
        set {
            this.extensionTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ComponentInUseType component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ExtensionTypeType {
    
    private bool itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extends", typeof(bool), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("implements", typeof(bool), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public bool Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("extends")]
    extends,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("implements")]
    implements,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class FusionsOfReplicatorsType {
    
    private FusionOfReplicatorsType[] fusionOfReplicatorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fusionOfReplicators", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public FusionOfReplicatorsType[] fusionOfReplicators {
        get {
            return this.fusionOfReplicatorsField;
        }
        set {
            this.fusionOfReplicatorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class FusionOfReplicatorsType {
    
    private string eRefField;
    
    private string[] originRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string eRef {
        get {
            return this.eRefField;
        }
        set {
            this.eRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] originRef {
        get {
            return this.originRefField;
        }
        set {
            this.originRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumeratorFromRecursionType {
    
    private string cRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableEntryType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableUnitSliceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableComponentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumerableUnitType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumerableType {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumerableEntryType : EnumerableType {
    
    private string cRefField;
    
    private string uRefField;
    
    private int indexField;
    
    private bool indexFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indexSpecified {
        get {
            return this.indexFieldSpecified;
        }
        set {
            this.indexFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumerableUnitSliceType : EnumerableType {
    
    private string uRefField;
    
    private string cRefField;
    
    private string sRefField;
    
    private int splitReplicaField;
    
    private bool splitReplicaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sRef {
        get {
            return this.sRefField;
        }
        set {
            this.sRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int splitReplica {
        get {
            return this.splitReplicaField;
        }
        set {
            this.splitReplicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool splitReplicaSpecified {
        get {
            return this.splitReplicaFieldSpecified;
        }
        set {
            this.splitReplicaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumerableComponentType : EnumerableType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumerableUnitType : EnumerableType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class EnumeratorType {
    
    private string[] originRefField;
    
    private EnumerableType[] linksField;
    
    private VisualElementAttributes visualDescriptionField;
    
    private EnumeratorFromRecursionType fromRecursionField;
    
    private string refField;
    
    private string varIdField;
    
    private int cardinalityField;
    
    private bool cardinalityFieldSpecified;
    
    private bool fromSplitField;
    
    public EnumeratorType() {
        this.varIdField = "*";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] originRef {
        get {
            return this.originRefField;
        }
        set {
            this.originRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("links", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EnumerableType[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EnumeratorFromRecursionType fromRecursion {
        get {
            return this.fromRecursionField;
        }
        set {
            this.fromRecursionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("*")]
    public string varId {
        get {
            return this.varIdField;
        }
        set {
            this.varIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cardinality {
        get {
            return this.cardinalityField;
        }
        set {
            this.cardinalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cardinalitySpecified {
        get {
            return this.cardinalityFieldSpecified;
        }
        set {
            this.cardinalityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fromSplit {
        get {
            return this.fromSplitField;
        }
        set {
            this.fromSplitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class VisualElementAttributes {
    
    private ColorComplexType colorField;
    
    private uint xField;
    
    private uint yField;
    
    private uint wField;
    
    private uint hField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ColorComplexType color {
        get {
            return this.colorField;
        }
        set {
            this.colorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint w {
        get {
            return this.wField;
        }
        set {
            this.wField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint h {
        get {
            return this.hField;
        }
        set {
            this.hField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ColorComplexType {
    
    private byte rField;
    
    private byte gField;
    
    private byte bField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte r {
        get {
            return this.rField;
        }
        set {
            this.rField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte g {
        get {
            return this.gField;
        }
        set {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitSliceType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class UnitRefType {
    
    private string cRefField;
    
    private string uRefField;
    
    private int replicaField;
    
    public UnitRefType() {
        this.cRefField = "this";
        this.replicaField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("this")]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int replica {
        get {
            return this.replicaField;
        }
        set {
            this.replicaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class UnitSliceType : UnitRefType {
    
    private VisualElementAttributes visualDescriptionField;
    
    private string[] portField;
    
    private string sliceNameField;
    
    private bool transitiveField;
    
    private bool transitiveFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sliceName {
        get {
            return this.sliceNameField;
        }
        set {
            this.sliceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool transitive {
        get {
            return this.transitiveField;
        }
        set {
            this.transitiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool transitiveSpecified {
        get {
            return this.transitiveFieldSpecified;
        }
        set {
            this.transitiveFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class UnitType {
    
    private UnitRefType superField;
    
    private UnitSliceType[] slicesField;
    
    private VisualElementAttributes visualDescriptionField;
    
    private string uRefField;
    
    private string iRefField;
    
    private bool privateField;
    
    private bool privateFieldSpecified;
    
    private bool visibleInterfaceField;
    
    public UnitType() {
        this.visibleInterfaceField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public UnitRefType super {
        get {
            return this.superField;
        }
        set {
            this.superField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public UnitSliceType[] slices {
        get {
            return this.slicesField;
        }
        set {
            this.slicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iRef {
        get {
            return this.iRefField;
        }
        set {
            this.iRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool @private {
        get {
            return this.privateField;
        }
        set {
            this.privateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool privateSpecified {
        get {
            return this.privateFieldSpecified;
        }
        set {
            this.privateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool visibleInterface {
        get {
            return this.visibleInterfaceField;
        }
        set {
            this.visibleInterfaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InterfaceParameterType {
    
    private string paridField;
    
    private string varidField;
    
    private string inameField;
    
    private string unameField;
    
    private int orderField;
    
    private bool orderFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parid {
        get {
            return this.paridField;
        }
        set {
            this.paridField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string varid {
        get {
            return this.varidField;
        }
        set {
            this.varidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iname {
        get {
            return this.inameField;
        }
        set {
            this.inameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uname {
        get {
            return this.unameField;
        }
        set {
            this.unameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class PortSliceType {
    
    private string sRefField;
    
    private string pRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sRef {
        get {
            return this.sRefField;
        }
        set {
            this.sRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pRef {
        get {
            return this.pRefField;
        }
        set {
            this.pRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InterfacePortType {
    
    private VisualElementAttributes visualDescriptionField;
    
    private PortSliceType[] sliceField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PortSliceType[] slice {
        get {
            return this.sliceField;
        }
        set {
            this.sliceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class SourceFileType {
    
    private string[] dependencyField;
    
    private string[] externalDependencyField;
    
    private string uriField;
    
    private string srcTypeField;
    
    private string fileTypeField;
    
    private string versionIdField;
    
    private string nameField;
    
    private string contentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] dependency {
        get {
            return this.dependencyField;
        }
        set {
            this.dependencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("externalDependency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] externalDependency {
        get {
            return this.externalDependencyField;
        }
        set {
            this.externalDependencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string srcType {
        get {
            return this.srcTypeField;
        }
        set {
            this.srcTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileType {
        get {
            return this.fileTypeField;
        }
        set {
            this.fileTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string versionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contents {
        get {
            return this.contentsField;
        }
        set {
            this.contentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class SourceType {
    
    private SourceFileType[] fileField;
    
    private string versionIdField;
    
    private string sourceTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("file", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SourceFileType[] file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string versionId {
        get {
            return this.versionIdField;
        }
        set {
            this.versionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourceType {
        get {
            return this.sourceTypeField;
        }
        set {
            this.sourceTypeField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionSignalType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionWaitType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionSkipType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionActivateType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorAltType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorParType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorSeqType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionType {
    
    private VisualElementAttributes visualDescriptionField;
    
    private string labelField;
    
    private uint repeatField;
    
    private bool repeatFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint repeat {
        get {
            return this.repeatField;
        }
        set {
            this.repeatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool repeatSpecified {
        get {
            return this.repeatFieldSpecified;
        }
        set {
            this.repeatFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionSignalType : ActionType {
    
    private string semaphoreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semaphore {
        get {
            return this.semaphoreField;
        }
        set {
            this.semaphoreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionWaitType : ActionType {
    
    private string semaphoreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semaphore {
        get {
            return this.semaphoreField;
        }
        set {
            this.semaphoreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionSkipType : ActionType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionActivateType : ActionType {
    
    private string sliceRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sliceRef {
        get {
            return this.sliceRefField;
        }
        set {
            this.sliceRefField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorAltType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorParType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActionCombinatorSeqType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionCombinatorType : ActionType {
    
    private ActionType[] actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("action", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ActionType[] action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionCombinatorAltType : ActionCombinatorType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionCombinatorParType : ActionCombinatorType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ActionCombinatorSeqType : ActionCombinatorType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InterfaceRefType {
    
    private string cRefField;
    
    private string iRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iRef {
        get {
            return this.iRefField;
        }
        set {
            this.iRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InterfaceSliceType {
    
    private InterfaceRefType originRefField;
    
    private VisualElementAttributes visualDescriptionField;
    
    private string isRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterfaceRefType originRef {
        get {
            return this.originRefField;
        }
        set {
            this.originRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isRef {
        get {
            return this.isRefField;
        }
        set {
            this.isRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InterfaceType {
    
    private InterfaceSliceType[] sliceField;
    
    private ActionType protocolField;
    
    private SourceType[] sourcesField;
    
    private VisualElementAttributes visualDescriptionField;
    
    private InterfacePortType[] portField;
    
    private string[] externalReferencesField;
    
    private InterfaceParameterType[] parameterField;
    
    private string iRefField;
    
    private int nArgsField;
    
    private bool nArgsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterfaceSliceType[] slice {
        get {
            return this.sliceField;
        }
        set {
            this.sliceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ActionType protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sources", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SourceType[] sources {
        get {
            return this.sourcesField;
        }
        set {
            this.sourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterfacePortType[] port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("externalReferences", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] externalReferences {
        get {
            return this.externalReferencesField;
        }
        set {
            this.externalReferencesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterfaceParameterType[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iRef {
        get {
            return this.iRefField;
        }
        set {
            this.iRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int nArgs {
        get {
            return this.nArgsField;
        }
        set {
            this.nArgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nArgsSpecified {
        get {
            return this.nArgsFieldSpecified;
        }
        set {
            this.nArgsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class RecursiveEntryType {
    
    private string cRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class SplitLinkType {
    
    private string cRefField;
    
    private string uRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class SplitType {
    
    private SplitLinkType[] splitLinkField;
    
    private string[] splitEnumeratorField;
    
    private string[] originRefField;
    
    private string eRefField;
    
    private int nField;
    
    private bool nFieldSpecified;
    
    private string cRefPermutationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("splitLink", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SplitLinkType[] splitLink {
        get {
            return this.splitLinkField;
        }
        set {
            this.splitLinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("splitEnumerator", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] splitEnumerator {
        get {
            return this.splitEnumeratorField;
        }
        set {
            this.splitEnumeratorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("originRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] originRef {
        get {
            return this.originRefField;
        }
        set {
            this.originRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string eRef {
        get {
            return this.eRefField;
        }
        set {
            this.eRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int n {
        get {
            return this.nField;
        }
        set {
            this.nField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nSpecified {
        get {
            return this.nFieldSpecified;
        }
        set {
            this.nFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRefPermutation {
        get {
            return this.cRefPermutationField;
        }
        set {
            this.cRefPermutationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class FusionType {
    
    private string[] cRefsField;
    
    private string pRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cRefs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] cRefs {
        get {
            return this.cRefsField;
        }
        set {
            this.cRefsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pRef {
        get {
            return this.pRefField;
        }
        set {
            this.pRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InnerRenamingType {
    
    private string cRefField;
    
    private string cOldNameField;
    
    private string cNewNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cOldName {
        get {
            return this.cOldNameField;
        }
        set {
            this.cOldNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cNewName {
        get {
            return this.cNewNameField;
        }
        set {
            this.cNewNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ParameterSupplyType {
    
    private string varNameField;
    
    private string cRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string varName {
        get {
            return this.varNameField;
        }
        set {
            this.varNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cRef {
        get {
            return this.cRefField;
        }
        set {
            this.cRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ParameterType {
    
    private string formFieldIdField;
    
    private string componentRefField;
    
    private string varNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formFieldId {
        get {
            return this.formFieldIdField;
        }
        set {
            this.formFieldIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string componentRef {
        get {
            return this.componentRefField;
        }
        set {
            this.componentRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string varName {
        get {
            return this.varNameField;
        }
        set {
            this.varNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class VersionType {
    
    private int field1Field;
    
    private bool field1FieldSpecified;
    
    private int field2Field;
    
    private bool field2FieldSpecified;
    
    private int field3Field;
    
    private bool field3FieldSpecified;
    
    private int field4Field;
    
    private bool field4FieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int field1 {
        get {
            return this.field1Field;
        }
        set {
            this.field1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool field1Specified {
        get {
            return this.field1FieldSpecified;
        }
        set {
            this.field1FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int field2 {
        get {
            return this.field2Field;
        }
        set {
            this.field2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool field2Specified {
        get {
            return this.field2FieldSpecified;
        }
        set {
            this.field2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int field3 {
        get {
            return this.field3Field;
        }
        set {
            this.field3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool field3Specified {
        get {
            return this.field3FieldSpecified;
        }
        set {
            this.field3FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int field4 {
        get {
            return this.field4Field;
        }
        set {
            this.field4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool field4Specified {
        get {
            return this.field4FieldSpecified;
        }
        set {
            this.field4FieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class UnitBoundsType {
    
    private VisualElementAttributes visualDescriptionField;
    
    private string uRefField;
    
    private uint replicaField;
    
    private bool replicaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uRef {
        get {
            return this.uRefField;
        }
        set {
            this.uRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint replica {
        get {
            return this.replicaField;
        }
        set {
            this.replicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool replicaSpecified {
        get {
            return this.replicaFieldSpecified;
        }
        set {
            this.replicaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ParameterRenaming {
    
    private string formFieldIdField;
    
    private string varNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formFieldId {
        get {
            return this.formFieldIdField;
        }
        set {
            this.formFieldIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string varName {
        get {
            return this.varNameField;
        }
        set {
            this.varNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InnerComponentType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class ComponentInUseType {
    
    private VisualElementAttributes visualDescriptionField;
    
    private ParameterRenaming[] parameterField;
    
    private InnerComponentType[] portField;
    
    private UnitBoundsType[] unitBoundsField;
    
    private string nameField;
    
    private string versionField;
    
    private string locationField;
    
    private string localRefField;
    
    private string hash_component_UIDField;
    
    private string parameter_idField;
    
    private string packageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public VisualElementAttributes visualDescription {
        get {
            return this.visualDescriptionField;
        }
        set {
            this.visualDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ParameterRenaming[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("port", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InnerComponentType[] port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("unitBounds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public UnitBoundsType[] unitBounds {
        get {
            return this.unitBoundsField;
        }
        set {
            this.unitBoundsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string localRef {
        get {
            return this.localRefField;
        }
        set {
            this.localRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hash_component_UID {
        get {
            return this.hash_component_UIDField;
        }
        set {
            this.hash_component_UIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameter_id {
        get {
            return this.parameter_idField;
        }
        set {
            this.parameter_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public partial class InnerComponentType : ComponentInUseType {
    
    private bool exposedField;
    
    private bool exposedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool exposed {
        get {
            return this.exposedField;
        }
        set {
            this.exposedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool exposedSpecified {
        get {
            return this.exposedFieldSpecified;
        }
        set {
            this.exposedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/HashComponent")]
public enum SupportedKinds {
    
    /// <remarks/>
    Data,
    
    /// <remarks/>
    Computation,
    
    /// <remarks/>
    Synchronizer,
    
    /// <remarks/>
    Architecture,
    
    /// <remarks/>
    Environment,
    
    /// <remarks/>
    Qualifier,
    
    /// <remarks/>
    Application,
    
    /// <remarks/>
    Enumerator,
}
