// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SAFeSWL {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    [System.Xml.Serialization.XmlRootAttribute("application", Namespace="http://www.example.org/instantiator", IsNullable=false)]
    public partial class InstanceType {
        
        private ComponentFunctorApplicationType contextual_typeField;
        
        private int facet_instanceField;
        
        private bool facet_instanceFieldSpecified;
        
        private UnitMappingType[] unit_mappingField;
        
        private FacetAddressType[] facet_addressField;
        
        private string instance_refField;
        
        /// <remarks/>
        public ComponentFunctorApplicationType contextual_type {
            get {
                return this.contextual_typeField;
            }
            set {
                this.contextual_typeField = value;
            }
        }
        
        /// <remarks/>
        public int facet_instance {
            get {
                return this.facet_instanceField;
            }
            set {
                this.facet_instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facet_instanceSpecified {
            get {
                return this.facet_instanceFieldSpecified;
            }
            set {
                this.facet_instanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit_mapping")]
        public UnitMappingType[] unit_mapping {
            get {
                return this.unit_mappingField;
            }
            set {
                this.unit_mappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facet_address")]
        public FacetAddressType[] facet_address {
            get {
                return this.facet_addressField;
            }
            set {
                this.facet_addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string instance_ref {
            get {
                return this.instance_refField;
            }
            set {
                this.instance_refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ComponentFunctorApplicationType {
        
        private ContextArgumentType[] argumentField;
        
        private string component_refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("argument")]
        public ContextArgumentType[] argument {
            get {
                return this.argumentField;
            }
            set {
                this.argumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string component_ref {
            get {
                return this.component_refField;
            }
            set {
                this.component_refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class ContextArgumentType {
        
        private object itemField;
        
        private string parameter_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(ComponentFunctorApplicationType))]
        [System.Xml.Serialization.XmlElementAttribute("variable", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parameter_id {
            get {
                return this.parameter_idField;
            }
            set {
                this.parameter_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_BindingAction {
        
        private SAFeSWL_Port[] peerField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("peer")]
        public SAFeSWL_Port[] peer {
            get {
                return this.peerField;
            }
            set {
                this.peerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortAction))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortEnvironment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortEnvironmentProvider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortEnvironmentUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Port {
        
        private string id_componentField;
        
        private string id_portField;
        
        private int facetField;
        
        private int facet_instanceField;
        
        private string wsdl_pathField;
        
        public SAFeSWL_Port() {
            this.facetField = 0;
            this.facet_instanceField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_component {
            get {
                return this.id_componentField;
            }
            set {
                this.id_componentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_port {
            get {
                return this.id_portField;
            }
            set {
                this.id_portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int facet_instance {
            get {
                return this.facet_instanceField;
            }
            set {
                this.facet_instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wsdl_path {
            get {
                return this.wsdl_pathField;
            }
            set {
                this.wsdl_pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_PortAction : SAFeSWL_Port {
        
        private SAFeSWL_Action[] actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action")]
        public SAFeSWL_Action[] action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Action {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortEnvironmentProvider))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_PortEnvironmentUser))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_PortEnvironment : SAFeSWL_Port {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_PortEnvironmentProvider : SAFeSWL_PortEnvironment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_PortEnvironmentUser : SAFeSWL_PortEnvironment {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_BindingService {
        
        private SAFeSWL_PortEnvironmentUser user_portField;
        
        private SAFeSWL_PortEnvironmentProvider provider_portField;
        
        private string nameField;
        
        /// <remarks/>
        public SAFeSWL_PortEnvironmentUser user_port {
            get {
                return this.user_portField;
            }
            set {
                this.user_portField = value;
            }
        }
        
        /// <remarks/>
        public SAFeSWL_PortEnvironmentProvider provider_port {
            get {
                return this.provider_portField;
            }
            set {
                this.provider_portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class ConnectorFacetType {
        
        private int facetField;
        
        private int multiplicityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int multiplicity {
            get {
                return this.multiplicityField;
            }
            set {
                this.multiplicityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Contract {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instantiation_type", typeof(InstanceType))]
        [System.Xml.Serialization.XmlElementAttribute("uri", typeof(string), DataType="anyURI")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Workflow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Computation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Platform))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_DataSource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Component {
        
        private SAFeSWL_PortEnvironmentUser[] user_portField;
        
        private SAFeSWL_PortEnvironmentProvider[] provider_portField;
        
        private SAFeSWL_Contract contractField;
        
        private string id_componentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("user_port")]
        public SAFeSWL_PortEnvironmentUser[] user_port {
            get {
                return this.user_portField;
            }
            set {
                this.user_portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider_port")]
        public SAFeSWL_PortEnvironmentProvider[] provider_port {
            get {
                return this.provider_portField;
            }
            set {
                this.provider_portField = value;
            }
        }
        
        /// <remarks/>
        public SAFeSWL_Contract contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_component {
            get {
                return this.id_componentField;
            }
            set {
                this.id_componentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Connector))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SAFeSWL_Computation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Workflow : SAFeSWL_Component {
        
        private SAFeSWL_PortAction[] action_portField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action_port")]
        public SAFeSWL_PortAction[] action_port {
            get {
                return this.action_portField;
            }
            set {
                this.action_portField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Connector : SAFeSWL_Workflow {
        
        private ConnectorFacetType[] facetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facet")]
        public ConnectorFacetType[] facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Computation : SAFeSWL_Workflow {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_Platform : SAFeSWL_Component {
        
        private string platform_addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string platform_address {
            get {
                return this.platform_addressField;
            }
            set {
                this.platform_addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    public partial class SAFeSWL_DataSource : SAFeSWL_Component {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class FacetAddressType {
        
        private int facet_instanceField;
        
        private bool facet_instanceFieldSpecified;
        
        private int facetField;
        
        private bool facetFieldSpecified;
        
        private string addressField;
        
        private int portField;
        
        private bool portFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int facet_instance {
            get {
                return this.facet_instanceField;
            }
            set {
                this.facet_instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facet_instanceSpecified {
            get {
                return this.facet_instanceFieldSpecified;
            }
            set {
                this.facet_instanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facetSpecified {
            get {
                return this.facetFieldSpecified;
            }
            set {
                this.facetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portSpecified {
            get {
                return this.portFieldSpecified;
            }
            set {
                this.portFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    public partial class UnitMappingType {
        
        private int[] nodeField;
        
        private int facet_instanceField;
        
        private bool facet_instanceFieldSpecified;
        
        private int facetField;
        
        private bool facetFieldSpecified;
        
        private string unit_idField;
        
        private int unit_indexField;
        
        public UnitMappingType() {
            this.unit_indexField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public int[] node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int facet_instance {
            get {
                return this.facet_instanceField;
            }
            set {
                this.facet_instanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facet_instanceSpecified {
            get {
                return this.facet_instanceFieldSpecified;
            }
            set {
                this.facet_instanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int facet {
            get {
                return this.facetField;
            }
            set {
                this.facetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool facetSpecified {
            get {
                return this.facetFieldSpecified;
            }
            set {
                this.facetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                this.unit_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int unit_index {
            get {
                return this.unit_indexField;
            }
            set {
                this.unit_indexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/instantiator")]
    [System.Xml.Serialization.XmlRootAttribute("unit_mapping", Namespace="http://www.example.org/instantiator", IsNullable=false)]
    public partial class UnitMappingDescriptionType {
        
        private UnitMappingType[] unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unit")]
        public UnitMappingType[] unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SAFe_architecture_V6")]
    [System.Xml.Serialization.XmlRootAttribute("architecture", Namespace="http://www.example.org/SAFe_architecture_V6", IsNullable=false)]
    public partial class SAFeSWL_Architecture {
        
        private SAFeSWL_Component applicationField;
        
        private SAFeSWL_Workflow workflowField;
        
        private SAFeSWL_Component[] solutionField;
        
        private SAFeSWL_BindingService[] service_bindingField;
        
        private SAFeSWL_BindingAction[] action_bindingField;
        
        private string application_nameField;
        
        /// <remarks/>
        public SAFeSWL_Component application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public SAFeSWL_Workflow workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("computation", typeof(SAFeSWL_Computation), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("connector", typeof(SAFeSWL_Connector), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("datasource", typeof(SAFeSWL_DataSource), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("platform", typeof(SAFeSWL_Platform), IsNullable=false)]
        public SAFeSWL_Component[] solution {
            get {
                return this.solutionField;
            }
            set {
                this.solutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("service_binding")]
        public SAFeSWL_BindingService[] service_binding {
            get {
                return this.service_bindingField;
            }
            set {
                this.service_bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action_binding")]
        public SAFeSWL_BindingAction[] action_binding {
            get {
                return this.action_bindingField;
            }
            set {
                this.action_bindingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string application_name {
            get {
                return this.application_nameField;
            }
            set {
                this.application_nameField = value;
            }
        }
    }
}
