namespace br.ufc.pargo.hpe.backend.DGAC.TCOL.grammar{

public enum CertifierOrchestrationOperation {

	ORCHESTRATION,
	SEQUENCEOPER, PARALLELOPER, SELECTOPER, SWITCHOPER, REPEATOPER,
	STARTOPER, WAITOPER, CANCELOPER, PERFORMOPER, SKIPOPER, BREAKOPER, CONTINUEOPER, 
	ACTION, ID,
	OPERATION,
	RESOLVE, DEPLOY, INSTANTIATE, RELEASE, COMPUTE,
		PORTID,
	ACTIONID,
	CHOICE,
}
}