//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/BackEndEnvironment")]
[System.Xml.Serialization.XmlRootAttribute("environment", Namespace="http://www.example.org/BackEndEnvironment", IsNullable=false)]
public partial class EnvironmentType {
    
    private DeployedComponentInfoType[] deployedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("deployed")]
    public DeployedComponentInfoType[] deployed {
        get {
            return this.deployedField;
        }
        set {
            this.deployedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/BackEndEnvironment")]
public partial class DeployedComponentInfoType {
    
    private string[] packageField;
    
    private string[] enumeratorField;
    
    private DeployedParameterType[] parameterField;
    
    private string nameField;
    
    private int cidField;
    
    private bool cidFieldSpecified;
    
    private string kindField;
    
    private bool abstractField;
    
    private bool abstractFieldSpecified;
    
    private string locationURIField;
    
    private int cidBaseField;
    
    private bool cidBaseFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("package")]
    public string[] package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("enumerator")]
    public string[] enumerator {
        get {
            return this.enumeratorField;
        }
        set {
            this.enumeratorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter")]
    public DeployedParameterType[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cid {
        get {
            return this.cidField;
        }
        set {
            this.cidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cidSpecified {
        get {
            return this.cidFieldSpecified;
        }
        set {
            this.cidFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool @abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool abstractSpecified {
        get {
            return this.abstractFieldSpecified;
        }
        set {
            this.abstractFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string locationURI {
        get {
            return this.locationURIField;
        }
        set {
            this.locationURIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int cidBase {
        get {
            return this.cidBaseField;
        }
        set {
            this.cidBaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cidBaseSpecified {
        get {
            return this.cidBaseFieldSpecified;
        }
        set {
            this.cidBaseFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/BackEndEnvironment")]
public partial class DeployedParameterType {
    
    private int actualField;
    
    private bool actualFieldSpecified;
    
    private int boundField;
    
    private DeployedParameterType[] parameterField;
    
    private string parameter_idField;
    
    /// <remarks/>
    public int actual {
        get {
            return this.actualField;
        }
        set {
            this.actualField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actualSpecified {
        get {
            return this.actualFieldSpecified;
        }
        set {
            this.actualFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int bound {
        get {
            return this.boundField;
        }
        set {
            this.boundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter")]
    public DeployedParameterType[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameter_id {
        get {
            return this.parameter_idField;
        }
        set {
            this.parameter_idField = value;
        }
    }
}
